#!usr/bin/python

import os
import time

print("\t\t\n\n\n\n")
os.system("tput setaf 3")
print "\t\t\t Welcome to File Command Line"
os.system("tput setaf 0")
print "\t\t\t!!**!!**!!**!!**!!**!!**!!**!!"
print " \t\t\t\t\t\t"
os.system("tput setaf 0")
print"""
Press 1: To Check The List Of Current Partition
Press 2: To Create A Partition
Press 3: To Enter New Partition
Press 4: To Enter The Size Of Partition
Press 5: To Save The Partition
Press 6: To Show The Partition List
Press 7: To Be Mount The Partition
Press 8: To Be Take  a Backup Of File System
Press 9: To Reboot The System
Press 10: To Check The List of Part For Delete
Press 11: To Delete The Partition
Press 12: To save a done Process
"""
p=raw_input("Follow This To be di it")
if int(p)==1:
   print"Enter C to Check The Current Partiton in Disk")
   os.system("fdisk -l")
elif int(p)==2:
   print("Enter P for Partition")
   os.system("fdisk /dev/sda | p")
elif int(p)==3:
   print("Enter N for new partition")
   os.system("n")
elif int(p)==4:
   fsize=raw_input("Enter The Fdisk Size  : ")
   os.system("n {0}".format(fsize))
elif int(p)==5:
    Print("Enter W  for Save A Partition : ")
    os.system("w")
elif int(p)==6:
     os.system("fdisk -l")
elif int(p)==7:
     print("Enter M for Mounting ")
     os.system(""mkdir /test | mount /dev/sda3 /test | ls -a /test")
elif int(p)==8
     os.system("cp /etc/fstab /etc/fstab.bk | vi /etc/fstab")
elif int(p)==9:
     os.system("reboot")
elif int(p)==10:
     print("Press Enter to Start The delete Partition")
     os.system(fdisk /dev/sda")
elif  int(p                         )==11:
     os.system("p | d")
elif int(p)==12:
     os.system("w")
else :
    print"Enter The Valid key"
